import { defineConfig, presetWind3 } from 'unocss';

export default defineConfig({
    presets: [
        presetWind3(),
    ],
    content: {
        filesystem: [
            './resources/views/**/*.blade.php',
            './resources/js/**/*.js',
        ],
    },
    theme: {
        colors: {
            latte: {
                rosewater: '#dc8a78',
                flamingo: '#dd7878',
                pink: '#ea76cb',
                mauve: '#8839ef',
                red: '#d20f39',
                maroon: '#e64553',
                peach: '#fe640b',
                yellow: '#df8e1d',
                green: '#40a02b',
                teal: '#179299',
                sky: '#04a5e5',
                sapphire: '#209fb5',
                blue: '#1e66f5',
                lavender: '#7287fd',
                text: '#4c4f69',
                subtext1: '#5c5f77',
                subtext0: '#6c6f85',
                overlay2: '#7c7f93',
                overlay1: '#8c8fa1',
                overlay0: '#9ca0b0',
                surface2: '#acb0be',
                surface1: '#bcc0cc',
                surface0: '#ccd0da',
                base: '#eff1f5',
                mantle: '#e6e9ef',
                crust: '#dce0e8',
            },
            'latte-surface0': '#ccd0da',
            'latte-surface1': '#bcc0cc',
            'latte-surface2': '#acb0be',
            'latte-overlay0': '#9ca0b0',
            'latte-overlay1': '#8c8fa1',
            'latte-overlay2': '#7c7f93',
            'latte-subtext0': '#6c6f85',
            'latte-subtext1': '#5c5f77',
        },
        fontFamily: {
            pixel: ['"Silkscreen"', '"Press Start 2P"', 'monospace'],
            sans: ['"Nunito"', 'system-ui', '-apple-system', 'sans-serif'],
            mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        },
    },
    shortcuts: [
        ['pixel-box', 'border-2 border-latte-text shadow-[2px_2px_0_0_#4c4f69]'],
        ['pixel-box-sm', 'border-1 border-latte-text shadow-[1px_1px_0_0_#4c4f69]'],
        ['pixel-box-lg', 'border-3 border-latte-text shadow-[4px_4px_0_0_#4c4f69]'],
        ['pixel-panel', 'bg-latte-base border-2 border-latte-surface2 shadow-[3px_3px_0_0_#bcc0cc] p-4'],
        ['pixel-btn', 'px-3 py-1.5 font-pixel text-xs tracking-wider transition-all select-none active:translate-x-0.5 active:translate-y-0.5 active:shadow-none cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed'],
        ['pixel-btn-primary', 'pixel-btn bg-latte-mauve text-latte-base hover:bg-latte-pink border-2 border-latte-text shadow-[2px_2px_0_0_#4c4f69]'],
        ['pixel-btn-secondary', 'pixel-btn bg-latte-surface0 text-latte-text hover:bg-latte-surface1 border-2 border-latte-text shadow-[2px_2px_0_0_#4c4f69]'],
        ['pixel-btn-accent', 'pixel-btn bg-latte-lavender text-latte-base hover:bg-latte-sapphire border-2 border-latte-text shadow-[2px_2px_0_0_#4c4f69]'],
        ['pixel-btn-rose', 'pixel-btn bg-latte-rosewater text-latte-text hover:bg-latte-flamingo border-2 border-latte-text shadow-[2px_2px_0_0_#4c4f69]'],
        ['pixel-btn-green', 'pixel-btn bg-latte-green text-latte-base hover:opacity-90 border-2 border-latte-text shadow-[2px_2px_0_0_#4c4f69]'],
    ],
    rules: [
        ['pixel-render', { 'image-rendering': 'pixelated' }],
        ['text-shadow-pixel', { 'text-shadow': '1px 1px 0px rgba(76, 79, 105, 0.4)' }],
    ],
});
